.TH TGFTP 1 "02 Oct 2012" "version 0.4.4" "User Commands"
.SH NAME
tgftp \- The GridFTP test script

.SH SYNOPSIS
.B tgftp
.BI "[--source|-s " "gsiftpSourceUrl" "]"
.BI "[--target|-t " "gsiftpTargetUrl" "]"
.BI "[--timeout " "gsiftpTimeout" "]"
.BI "[--log-filename " "gsiftpTransferLogFilename" "]"
.BI "[--log-comment " "gsiftpTransferLogComment" "]"
.BI "[--pre-command " "gsiftpTransferPreCommand" "]"
.BI "[--post-command " "gsiftpTransferPostCommand" "]"
.BI "[-- " "gsiftpParameters" "]"

.B tgftp
.BI "--source|-s " "gsiftpSourceUrl"
.BI "--target|-t " "gsiftpTargetUrl"
.B --connection-test|-c

.B tgftp
.BI "--source|-s " "gsiftpSourceUrl"
.BI "--target|-t " "gsiftpTargetUrl"
.B --auto-tune|-a

.B tgftp
.BI "--batchfile|-f " "gsiftpBatchfile"

.SH DESCRIPTION
.B tgftp
is a wrapper script for
.B globus-url-copy (guc)
to ease testing and documentation of GridFTP performance for specific
connections. The generated
.B guc
command, its output and the reached performance are logged to a file named like
the following:

.I yyyymmdd_H:Mh_$$_testgftp.sh.log

.I $$
is resolved to the PID of the tgftp process. Additionally the output of the
.B guc
command and the performance (transfer rate) is printed out to screen.

.SH NOTES
Because this tool includes the time needed for establishing the connection (total time needed for
the transfer), the transfer rates may vary from the rates that the
.B guc
command prints out - especially for short transfers. Additionally this tool can
only calculate the transfer rate if a 
.BI "-len|-partial-length " "length " "guc"
param is present.

.SH MODES
.B tgftp
has several modes of operation:

.TP 10
.B SINGLE TEST
Test a single connection.

.TP
.B CONNECTION TEST
Just make a connection test.

.TP
.B AUTO-TUNING
This will try various
.B guc
parameter configurations and determine the best performing combination for a
specific connection.

.TP
.B BATCH
Test multiple connections one after another.

.SH OPTIONS
The options are as follows:

.TP 10
.B General Options:

.TP
.BI "[--source|-s " "gsiftpSourceUrl" "]"
Determine the source URL for the transfer to test. If the 
.I "gsiftpParameters "
contain a "-f"  and provide a file with guc source and destination URLs, this
option can be omitted.

.TP
.BI "[--target|-t " "gsiftpTargetUrl" "]"
Determine the target URL for the transfer to test. If the 
.I "gsiftpParameters "
contain a "-f"  and provide a file  with guc source and destination URLs, this
option can be omitted.

.TP
.B "[--force-log-overwrite]"
By default tgftp refuses to overwrite existing tgftp logfiles. This option
forces overwriting of existing tgtfp logfiles.

.TP
.B [--help]
Prints out a help message.

.TP
.B [--help-batchfile]
Prints out the help about batchfiles.

.TP
.B [--version|-V]
Prints out version information.

.TP
.B SINGLE TEST Mode:

.TP 
.BI "[--timeout " "gsiftpTimeout" "]"
Determine the time in seconds,
.B tgftp
waits before it kills the guc command. By default no timeout is set. This is
also true if set to "0".

.TP
.BI "[--log-filename " "gsiftpTransferLogFilename" "]"
Determine the filename (including extension) of the logfile. The filename has to
be enclosed by double quotes. If not specified the default naming is used.

.TP
.BI "[--log-comment " "gsiftpTransferLogComment" "]"
Add a comment to the log. The comment has to be enclosed by double quotes. This
can also be a command like "cat PRE_COMMAND_OUTPUT.txt", which enables to
include output of the pre-command in the logfile (for example network params of
the target system or traceroute output, etc.). If not specified no comment is
added. Text only comments, meaning no command should be called, have to be
preceded by "#"!

.TP
.BI "[--pre-command " "gsiftpTransferPreCommand" "]"
Determine the filename of the command that should be executed before the test
(command must be executable and	path must be included). Must be enclosed by
double quotes. A pre-command may consist of multiple commands included in one
script. If not specified no additional command will be excuted before the test.

.TP
.BI "[--post-command " "gsiftpTransferPostCommand" "]"
Determine the filename of the command that should be executed after the test
(command must be executable and	path must be included). Must be enclosed by
double quotes.A post-command may consist of multiple commands included in one
script. If not specified no additional command will be excuted after the test.

.TP
.BI "[-- " "gsiftpParameters" "]"
Determine the guc parameters that should be used for the test. Notice the space
between 
.B --
and the actual parameters. To calculate the transfer rate at least
.BI "-len|-partial-length " "length"
must be specified. If this is not needed, the
.BI "-len|-partial-length " "length"
parameter can be omitted completely.

.TP
.B CONNECTION TEST Mode:

.TP
.B --connection-test|-c
Just do a connection test. This test does only transfer 1 Byte and logs the full
connection process. This implies 
.B -dbg
and
.B -vb
for the resulting 
.B guc
command. Additionally the timeout is set to 30 seconds. If this parameter is
used, all other parameters except 
.B --source
and
.B --target
are ignored.

.TP
.B AUTO-TUNING Mode:

.TP
.B --auto-tune|-a
Determine the best performing
.B guc
parameter configuration for the current source and target URLs.

.TP
.B BATCH Mode:

.TP
.BI "--batchfile|-f " "gsiftpBatchfile"
Determine the batchfile containing the parameter values for the tests to be
batch processed. If this parameter is used, all other parameters are ignored.

.SH EXAMPLES
The following command:
.LP
.nf
    tgftp -s file:///dev/zero -t gsiftp://localhost:2811/dev/null
.fi
.LP
results in the following
.B guc
command:
.LP
.nf
    globus-url-copy file:///dev/zero gsiftp://localhost:2811/dev/null
.fi
.LP

The following command will determine the congestion protocol that is used
locally before starting the test and include the output of the pre-command in
the comment of the logfile:
.LP
.nf
    tgftp -s file:///dev/zero -t gsiftp://gridftp-host.domain:2811/dev/null \\
          --log-comment 'cat PRE_COMMAND_OUTPUT.txt' \\
          --pre-command 'sysctl -n net.ipv4.tcp_congestion_control > PRE_COMMAND_OUTPUT.txt' \\
          -- -len 1M
.nf
.LP

The following command will initiate multiple tests (one after another) with the
parameter values included in "tgftp_tests.csv":
.LP
.nf
    tgftp -f tgftp_tests.csv
.fi
.LP


.SH AUTHOR
Frank Scheiner

.SH "SEE ALSO"
.BR tgftp_log (1)

